# Generated by Django 3.1.1 on 2020-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapi',
            name='email',
            field=models.EmailField(default='jhondoe@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
