# Generated by Django 3.1.1 on 2020-10-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_userapi_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApi',
        ),
    ]
